#!/bin/bash

#Switching the WI-FI network card to monitor mode

echo " "
echo "\e[1;32mACTIVATING MONITOR MODE IN\e[0m" $1
echo " "

airmon-ng check kill $1 >/dev/null
airmon-ng start $1 >/dev/null
iw dev

#Change the MAC of the WI-FI network card to a random MAC

echo " "
echo "\e[1;32mCHANGING MAC ADDRESS OF WI-FI NETWORK CARD\e[0m"
echo " "

ifconfig $1 down
macchanger -a $1 

#ncreasing the TX power of the WI-FI network card

echo " "
echo "\e[1;32mHANGING TRANSMISSION POWER TO 30dBm\e[0m"
echo " "

iw reg set GY #the framework of legislation applied is changed
iw $1 set txpower fixed 3000 #the transmitting power is changed to 30 dBm
ifconfig $1 up
iw dev
